# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/хуйня/kumir2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/хуйня/kumir2/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/хуйня/kumir2/build/CMakeFiles /data/data/com.termux/files/home/хуйня/kumir2/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/хуйня/kumir2/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExtensionSystem

# Build rule for target.
ExtensionSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExtensionSystem
.PHONY : ExtensionSystem

# fast build rule for target.
ExtensionSystem/fast:
	$(MAKE) $(MAKESILENT) -f src/kumir2-libs/extensionsystem/CMakeFiles/ExtensionSystem.dir/build.make src/kumir2-libs/extensionsystem/CMakeFiles/ExtensionSystem.dir/build
.PHONY : ExtensionSystem/fast

#=============================================================================
# Target rules for targets named DataFormats

# Build rule for target.
DataFormats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DataFormats
.PHONY : DataFormats

# fast build rule for target.
DataFormats/fast:
	$(MAKE) $(MAKESILENT) -f src/kumir2-libs/dataformats/CMakeFiles/DataFormats.dir/build.make src/kumir2-libs/dataformats/CMakeFiles/DataFormats.dir/build
.PHONY : DataFormats/fast

#=============================================================================
# Target rules for targets named ErrorMessages

# Build rule for target.
ErrorMessages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ErrorMessages
.PHONY : ErrorMessages

# fast build rule for target.
ErrorMessages/fast:
	$(MAKE) $(MAKESILENT) -f src/kumir2-libs/errormessages/CMakeFiles/ErrorMessages.dir/build.make src/kumir2-libs/errormessages/CMakeFiles/ErrorMessages.dir/build
.PHONY : ErrorMessages/fast

#=============================================================================
# Target rules for targets named Widgets

# Build rule for target.
Widgets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Widgets
.PHONY : Widgets

# fast build rule for target.
Widgets/fast:
	$(MAKE) $(MAKESILENT) -f src/kumir2-libs/widgets/CMakeFiles/Widgets.dir/build.make src/kumir2-libs/widgets/CMakeFiles/Widgets.dir/build
.PHONY : Widgets/fast

#=============================================================================
# Target rules for targets named DocBookViewer

# Build rule for target.
DocBookViewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DocBookViewer
.PHONY : DocBookViewer

# fast build rule for target.
DocBookViewer/fast:
	$(MAKE) $(MAKESILENT) -f src/kumir2-libs/docbookviewer/CMakeFiles/DocBookViewer.dir/build.make src/kumir2-libs/docbookviewer/CMakeFiles/DocBookViewer.dir/build
.PHONY : DocBookViewer/fast

#=============================================================================
# Target rules for targets named Editor

# Build rule for target.
Editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Editor
.PHONY : Editor

# fast build rule for target.
Editor/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/editor/CMakeFiles/Editor.dir/build.make src/plugins/editor/CMakeFiles/Editor.dir/build
.PHONY : Editor/fast

#=============================================================================
# Target rules for targets named CoreGUI

# Build rule for target.
CoreGUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CoreGUI
.PHONY : CoreGUI

# fast build rule for target.
CoreGUI/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/coregui/CMakeFiles/CoreGUI.dir/build.make src/plugins/coregui/CMakeFiles/CoreGUI.dir/build
.PHONY : CoreGUI/fast

#=============================================================================
# Target rules for targets named CourseManager

# Build rule for target.
CourseManager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CourseManager
.PHONY : CourseManager

# fast build rule for target.
CourseManager/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/coursemanager/CMakeFiles/CourseManager.dir/build.make src/plugins/coursemanager/CMakeFiles/CourseManager.dir/build
.PHONY : CourseManager/fast

#=============================================================================
# Target rules for targets named KumirAnalizer

# Build rule for target.
KumirAnalizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KumirAnalizer
.PHONY : KumirAnalizer

# fast build rule for target.
KumirAnalizer/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/kumiranalizer/CMakeFiles/KumirAnalizer.dir/build.make src/plugins/kumiranalizer/CMakeFiles/KumirAnalizer.dir/build
.PHONY : KumirAnalizer/fast

#=============================================================================
# Target rules for targets named KumirCodeGenerator

# Build rule for target.
KumirCodeGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KumirCodeGenerator
.PHONY : KumirCodeGenerator

# fast build rule for target.
KumirCodeGenerator/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/kumircodegenerator/CMakeFiles/KumirCodeGenerator.dir/build.make src/plugins/kumircodegenerator/CMakeFiles/KumirCodeGenerator.dir/build
.PHONY : KumirCodeGenerator/fast

#=============================================================================
# Target rules for targets named KumirCodeRun

# Build rule for target.
KumirCodeRun: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KumirCodeRun
.PHONY : KumirCodeRun

# fast build rule for target.
KumirCodeRun/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/kumircoderun/CMakeFiles/KumirCodeRun.dir/build.make src/plugins/kumircoderun/CMakeFiles/KumirCodeRun.dir/build
.PHONY : KumirCodeRun/fast

#=============================================================================
# Target rules for targets named KumirCompilerTool

# Build rule for target.
KumirCompilerTool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KumirCompilerTool
.PHONY : KumirCompilerTool

# fast build rule for target.
KumirCompilerTool/fast:
	$(MAKE) $(MAKESILENT) -f src/plugins/kumircompilertool/CMakeFiles/KumirCompilerTool.dir/build.make src/plugins/kumircompilertool/CMakeFiles/KumirCompilerTool.dir/build
.PHONY : KumirCompilerTool/fast

#=============================================================================
# Target rules for targets named Actor_Colorer

# Build rule for target.
Actor_Colorer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Actor_Colorer
.PHONY : Actor_Colorer

# fast build rule for target.
Actor_Colorer/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/_colorer/CMakeFiles/Actor_Colorer.dir/build.make src/actors/_colorer/CMakeFiles/Actor_Colorer.dir/build
.PHONY : Actor_Colorer/fast

#=============================================================================
# Target rules for targets named ActorComplexNumbers

# Build rule for target.
ActorComplexNumbers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorComplexNumbers
.PHONY : ActorComplexNumbers

# fast build rule for target.
ActorComplexNumbers/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/complexnumbers/CMakeFiles/ActorComplexNumbers.dir/build.make src/actors/complexnumbers/CMakeFiles/ActorComplexNumbers.dir/build
.PHONY : ActorComplexNumbers/fast

#=============================================================================
# Target rules for targets named ActorDraw

# Build rule for target.
ActorDraw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorDraw
.PHONY : ActorDraw

# fast build rule for target.
ActorDraw/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/draw/CMakeFiles/ActorDraw.dir/build.make src/actors/draw/CMakeFiles/ActorDraw.dir/build
.PHONY : ActorDraw/fast

#=============================================================================
# Target rules for targets named ActorGrasshopper

# Build rule for target.
ActorGrasshopper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorGrasshopper
.PHONY : ActorGrasshopper

# fast build rule for target.
ActorGrasshopper/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/grasshopper/CMakeFiles/ActorGrasshopper.dir/build.make src/actors/grasshopper/CMakeFiles/ActorGrasshopper.dir/build
.PHONY : ActorGrasshopper/fast

#=============================================================================
# Target rules for targets named ActorIsometricRobot

# Build rule for target.
ActorIsometricRobot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorIsometricRobot
.PHONY : ActorIsometricRobot

# fast build rule for target.
ActorIsometricRobot/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/isometricrobot/CMakeFiles/ActorIsometricRobot.dir/build.make src/actors/isometricrobot/CMakeFiles/ActorIsometricRobot.dir/build
.PHONY : ActorIsometricRobot/fast

#=============================================================================
# Target rules for targets named ActorKeyboard

# Build rule for target.
ActorKeyboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorKeyboard
.PHONY : ActorKeyboard

# fast build rule for target.
ActorKeyboard/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/keyboard/CMakeFiles/ActorKeyboard.dir/build.make src/actors/keyboard/CMakeFiles/ActorKeyboard.dir/build
.PHONY : ActorKeyboard/fast

#=============================================================================
# Target rules for targets named ActorPainter

# Build rule for target.
ActorPainter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorPainter
.PHONY : ActorPainter

# fast build rule for target.
ActorPainter/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/painter/CMakeFiles/ActorPainter.dir/build.make src/actors/painter/CMakeFiles/ActorPainter.dir/build
.PHONY : ActorPainter/fast

#=============================================================================
# Target rules for targets named ActorRobot

# Build rule for target.
ActorRobot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorRobot
.PHONY : ActorRobot

# fast build rule for target.
ActorRobot/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/robot/CMakeFiles/ActorRobot.dir/build.make src/actors/robot/CMakeFiles/ActorRobot.dir/build
.PHONY : ActorRobot/fast

#=============================================================================
# Target rules for targets named ActorTurtle

# Build rule for target.
ActorTurtle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorTurtle
.PHONY : ActorTurtle

# fast build rule for target.
ActorTurtle/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/turtle/CMakeFiles/ActorTurtle.dir/build.make src/actors/turtle/CMakeFiles/ActorTurtle.dir/build
.PHONY : ActorTurtle/fast

#=============================================================================
# Target rules for targets named ActorVodoley

# Build rule for target.
ActorVodoley: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ActorVodoley
.PHONY : ActorVodoley

# fast build rule for target.
ActorVodoley/fast:
	$(MAKE) $(MAKESILENT) -f src/actors/vodoley/CMakeFiles/ActorVodoley.dir/build.make src/actors/vodoley/CMakeFiles/ActorVodoley.dir/build
.PHONY : ActorVodoley/fast

#=============================================================================
# Target rules for targets named kumir2-classic

# Build rule for target.
kumir2-classic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-classic
.PHONY : kumir2-classic

# fast build rule for target.
kumir2-classic/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-classic/CMakeFiles/kumir2-classic.dir/build.make src/app/kumir2-classic/CMakeFiles/kumir2-classic.dir/build
.PHONY : kumir2-classic/fast

#=============================================================================
# Target rules for targets named kumir2-highgrade

# Build rule for target.
kumir2-highgrade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-highgrade
.PHONY : kumir2-highgrade

# fast build rule for target.
kumir2-highgrade/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-highgrade/CMakeFiles/kumir2-highgrade.dir/build.make src/app/kumir2-highgrade/CMakeFiles/kumir2-highgrade.dir/build
.PHONY : kumir2-highgrade/fast

#=============================================================================
# Target rules for targets named kumir2-ide

# Build rule for target.
kumir2-ide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-ide
.PHONY : kumir2-ide

# fast build rule for target.
kumir2-ide/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-ide/CMakeFiles/kumir2-ide.dir/build.make src/app/kumir2-ide/CMakeFiles/kumir2-ide.dir/build
.PHONY : kumir2-ide/fast

#=============================================================================
# Target rules for targets named kumir2-teacher

# Build rule for target.
kumir2-teacher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-teacher
.PHONY : kumir2-teacher

# fast build rule for target.
kumir2-teacher/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-teacher/CMakeFiles/kumir2-teacher.dir/build.make src/app/kumir2-teacher/CMakeFiles/kumir2-teacher.dir/build
.PHONY : kumir2-teacher/fast

#=============================================================================
# Target rules for targets named kumir2-checkcourse

# Build rule for target.
kumir2-checkcourse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-checkcourse
.PHONY : kumir2-checkcourse

# fast build rule for target.
kumir2-checkcourse/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-checkcourse/CMakeFiles/kumir2-checkcourse.dir/build.make src/app/kumir2-checkcourse/CMakeFiles/kumir2-checkcourse.dir/build
.PHONY : kumir2-checkcourse/fast

#=============================================================================
# Target rules for targets named kumir2-bc

# Build rule for target.
kumir2-bc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-bc
.PHONY : kumir2-bc

# fast build rule for target.
kumir2-bc/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-bc/CMakeFiles/kumir2-bc.dir/build.make src/app/kumir2-bc/CMakeFiles/kumir2-bc.dir/build
.PHONY : kumir2-bc/fast

#=============================================================================
# Target rules for targets named kumir2-xrun

# Build rule for target.
kumir2-xrun: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-xrun
.PHONY : kumir2-xrun

# fast build rule for target.
kumir2-xrun/fast:
	$(MAKE) $(MAKESILENT) -f src/app/kumir2-xrun/CMakeFiles/kumir2-xrun.dir/build.make src/app/kumir2-xrun/CMakeFiles/kumir2-xrun.dir/build
.PHONY : kumir2-xrun/fast

#=============================================================================
# Target rules for targets named pictomir2course

# Build rule for target.
pictomir2course: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pictomir2course
.PHONY : pictomir2course

# fast build rule for target.
pictomir2course/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/pictomir2course/CMakeFiles/pictomir2course.dir/build.make src/tools/pictomir2course/CMakeFiles/pictomir2course.dir/build
.PHONY : pictomir2course/fast

#=============================================================================
# Target rules for targets named docbook2latex

# Build rule for target.
docbook2latex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docbook2latex
.PHONY : docbook2latex

# fast build rule for target.
docbook2latex/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/docbook2latex/CMakeFiles/docbook2latex.dir/build.make src/tools/docbook2latex/CMakeFiles/docbook2latex.dir/build
.PHONY : docbook2latex/fast

#=============================================================================
# Target rules for targets named kumir2-open

# Build rule for target.
kumir2-open: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-open
.PHONY : kumir2-open

# fast build rule for target.
kumir2-open/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/open/CMakeFiles/kumir2-open.dir/build.make src/tools/open/CMakeFiles/kumir2-open.dir/build
.PHONY : kumir2-open/fast

#=============================================================================
# Target rules for targets named kumir2-courseeditor

# Build rule for target.
kumir2-courseeditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-courseeditor
.PHONY : kumir2-courseeditor

# fast build rule for target.
kumir2-courseeditor/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/courseeditor/CMakeFiles/kumir2-courseeditor.dir/build.make src/tools/courseeditor/CMakeFiles/kumir2-courseeditor.dir/build
.PHONY : kumir2-courseeditor/fast

#=============================================================================
# Target rules for targets named kumir2-run

# Build rule for target.
kumir2-run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kumir2-run
.PHONY : kumir2-run

# fast build rule for target.
kumir2-run/fast:
	$(MAKE) $(MAKESILENT) -f src/tools/run/CMakeFiles/kumir2-run.dir/build.make src/tools/run/CMakeFiles/kumir2-run.dir/build
.PHONY : kumir2-run/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ActorComplexNumbers"
	@echo "... ActorDraw"
	@echo "... ActorGrasshopper"
	@echo "... ActorIsometricRobot"
	@echo "... ActorKeyboard"
	@echo "... ActorPainter"
	@echo "... ActorRobot"
	@echo "... ActorTurtle"
	@echo "... ActorVodoley"
	@echo "... Actor_Colorer"
	@echo "... CoreGUI"
	@echo "... CourseManager"
	@echo "... DataFormats"
	@echo "... DocBookViewer"
	@echo "... Editor"
	@echo "... ErrorMessages"
	@echo "... ExtensionSystem"
	@echo "... KumirAnalizer"
	@echo "... KumirCodeGenerator"
	@echo "... KumirCodeRun"
	@echo "... KumirCompilerTool"
	@echo "... Widgets"
	@echo "... docbook2latex"
	@echo "... kumir2-bc"
	@echo "... kumir2-checkcourse"
	@echo "... kumir2-classic"
	@echo "... kumir2-courseeditor"
	@echo "... kumir2-highgrade"
	@echo "... kumir2-ide"
	@echo "... kumir2-open"
	@echo "... kumir2-run"
	@echo "... kumir2-teacher"
	@echo "... kumir2-xrun"
	@echo "... pictomir2course"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

